import { BarChart, BoxPlot, BasicChart, LineChart, MultiLine } from './charts';
import {
  BasicChartProps,
  BasicChartState,
  IGradientUnits,
  TextAnchor,
} from './types';
import {
  AxisConfig,
  BarChartProps,
  BoxPlotPress,
  BoxPlotProps,
  IBarChartTooltipConfig,
  ILinearGradient,
  ILineTooltipConfig,
  IOutlier,
  IStop,
  MultiLineData,
  MultiLineProps,
  LineChartProps,
} from './interfaces';
import {
  getRandomValueFromArray,
  newShade,
  quickSort,
  separateData,
} from './utils';

import {
  asc,
  desc,
  sum,
  max,
  min,
  range,
  mean,
  median,
  quartile,
  IQR,
  Outliers,
  maxWithoutOutliers,
  minWithoutOutliers,
  unique,
} from './helpers';

export const multiply = (a: number, b: number) => a * b;

export {
  asc,
  AxisConfig,
  BarChart,
  BarChartProps,
  BasicChart,
  BasicChartProps,
  BasicChartState,
  BoxPlot,
  BoxPlotPress,
  BoxPlotProps,
  desc,
  getRandomValueFromArray,
  IGradientUnits,
  IBarChartTooltipConfig,
  ILinearGradient,
  ILineTooltipConfig,
  IOutlier,
  IStop,
  IQR,
  LineChart,
  LineChartProps,
  max,
  maxWithoutOutliers,
  mean,
  median,
  min,
  minWithoutOutliers,
  MultiLine,
  MultiLineData,
  MultiLineProps,
  newShade,
  separateData,
  sum,
  Outliers,
  range,
  TextAnchor,
  quartile,
  quickSort,
  unique,
};
